### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xab in position 16: illegal multibyte sequence

### ISSUE THREAD

**Issue by yidasanqian** [BMPixel/moffee#14]
exception stack：
```
moffee live D:\Develop\IdeaProjects\azs-platform\doc\前后端对话交互规范（http方式）.md
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\XX\.local\bin\moffee.exe\__main__.py", line 7, in <module>
  File "C:\Users\XX\pipx\venvs\moffee\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\pipx\venvs\moffee\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\XX\pipx\venvs\moffee\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\pipx\venvs\moffee\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\pipx\venvs\moffee\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\pipx\venvs\moffee\Lib\site-packages\moffee\cli.py", line 96, in live
    run(markdown, output=None, live=True)
  File "C:\Users\XX\pipx\venvs\moffee\Lib\site-packages\moffee\cli.py", line 15, in run
    options = read_options(md)
              ^^^^^^^^^^^^^^^^
  File "C:\Users\XX\pipx\venvs\moffee\Lib\site-packages\moffee\builder.py", line 13, in read_options
    document = f.read()
               ^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 10: illegal multibyte sequence
```
HOW TO FIX ?

**Comment by honglizhu2024** [comment]
I noticed that the current version of your project does not support Chinese encoding (like the 'gbk' bugs). As a result, users who work primarily with Chinese characters are unable to fully utilize the project's features. In light of this, I kindly request that you consider adding Chinese encoding support to your project.

Here are a few reasons why Chinese encoding support would be beneficial:
1. Expanding the user base: Adding Chinese encoding support would make your project accessible to a broader audience, particularly in regions where Chinese is the primary language.
2. Enhancing user experience: Users who work with Chinese characters would greatly appreciate the ability to use your project without encountering encoding issues.
3. Fostering a more inclusive community: By accommodating users from different language backgrounds, your project will become more inclusive and diverse.
I understand that adding new features and support can be a time-consuming process. If you require any assistance or have any questions regarding Chinese encoding, please feel free to reach out to me. I would be more than happy to help in any way I can.

**Comment by MYJ695** [comment]
Based on my experience, you can modify the 'builder.py' file located in the 'moffee' directory, specifically lines 12 and 100 of the 'fread' function, by adding the following code snippet: encoding = 'utf-8'

such as : with open(document_path,encoding = 'utf-8') as f:

**Comment by WingLoong233** [comment]
1) create a new markdown document, 
2) select Encoding -> reopen with encoding -> gbk, 
3)  select "gbk",
4) copy all content from the old 'utf-8' formatted document to a new 'gbk' formatted file.

**Comment by Wing900** [comment]
I'm also encountering this encoding issue on Chinese Windows system. Here's my error message:
UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 37: illegal multibyte sequence

I can confirm that adding `encoding='utf-8'` parameter in `builder.py` fixes the issue:

1. In `read_options` function:
```python
def read_options(document_path) -> PageOption:
    with open(document_path, "r", encoding='utf-8') as f:
        document = f.read()
2.In build function:
def build(...):
    with open(document_path, encoding='utf-8') as f:
        document = f.read()

This modification ensures correct handling of UTF-8 encoded files containing Chinese characters on Windows systems where GBK is the default encoding.

**Comment by BMPixel** [comment]
In newest version v0.2.7, the fix has been patched. Sorry for the waiting!

**Comment by ahhhhwei** [comment]
thank you.&nbsp;I really like the Moffee tool and wish it continued popularity.



---Original---
From: "Wenbo ***@***.***&gt;
Date: Fri, Nov 22, 2024 18:24 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [BMPixel/moffee] UnicodeDecodeError: 'gbk' codec can't decodebyte 0xab in position 16: illegal multibyte sequence (Issue #14)




 
In newest version v0.2.7, the fix has been patched. Sorry for the waiting!
