### ISSUE TITLE
Suggestion: Add a comparison with Marp

### ISSUE THREAD

**Issue by Huanshere** [BMPixel/moffee#2]
Suggestion: Add a comparison with Marp in the README, as Marp is a well-known similar project that many people are familiar with.

**Comment by BMPixel** [comment]
Good idea! Currently I don’t view moffee as feature-completed. Many useful features and optimizations are being implemented. I will add a comparison section after a few more updates.

2024 年 8 月 16 日星期五 8:13 上午, Huanyu ***@***.***(mailto:2024 年 8 月 16 日星期五 8:13 上午, Huanyu <<a href=)> 来信：
