### ISSUE TITLE
how to generate a ppt?

### ISSUE THREAD

**Issue by ArlanCooper** [BMPixel/moffee#6]
**Is your feature request related to a problem? Please describe.**

there is not the code to show how to generate a ppt by use moffee?can you write one?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by BMPixel** [comment]
You're right that there is no way to generate a ppt right now. I'm working on it. However as far as I know, this won't be a easy feature as Powerpoint and HTML are so different.
