### ISSUE TITLE
VSCode extension

### ISSUE THREAD

**Issue by ZhikangNiu** [BMPixel/moffee#8]
Maybe we need a VSCode extension? 
right is markdown
left is slides?

**Comment by KotorinMinami** [comment]
Agree, preview in VSCode might be a good feature

**Comment by BMPixel** [comment]
Thank you for your suggestions! However due to my time and target, I will focus on refining the parsing system for next a few months. Before VSCode, I might make a website to support split view of code and slides, So moffee can work without installing on local machines.
