### ISSUE TITLE
Please develop a EXTENSION on the VS code.

### ISSUE THREAD

**Issue by H-Lumos** [BMPixel/moffee#9]
Slides making is a time-consuming things for me, a graduate student. I had a long time using beamer because of my favour of markdown, however, the f**king multifarious syntax is really a torture for me. Then I turn to office PPT, however, figures alignment tired me. Figures, tables, formulas should be added to the slide with only a few words, layout horizontally, vertically should be done with a few words. So I am attracted by moffee at the moment I see the brief clear syntax to implement the necessary features. The only shortage is I have to open a internet page to have the preview of the slides, this should be done on one platform, like VS code. Looking forward to your **EXTENSION** on VS code. LOVE from a graduate student.

**Comment by BMPixel** [comment]
Thank you. I will implement a VSCode extension when I have more time.
